dataset:
  name: ks
  integration_method: RK4
  duration: 0.4
  dt_num: 0.2
  dt_factor: 1
  batch_size: 128
  nb_traj_train: 512
  nb_traj_val: 128
  num_steps_max: 140

model:
  name: node
  gamma: 0.0
  phy_option: none_sup_accnorm
  aug_option: true
  architecture: "mlp"
  hidden: 200
  init_gain: 1.0
  integration_method: RK4
  dim_state: 256

train:
  lr: 1e-3
  niter: 1
  min_op: l2
  reg_loss_name: lip
  norm: False
  lambda0: 1e-3
  tau2: 0.0
  aux_loss_names: ["lip"]
  log_param_error: false # when hybrid
  nlog: 5
  nval: 5 
  curriculum: no_curr
  opt_mode: traj
  finite_diff: forward
  nepoch: 1000

experiment:
  path: data_exp/KS_gridsearch

logging:
  use_wandb: true
  project: ksICML
