dataset:
  name: doublependulum
  integration_method: RK4
  duration: 0.1
  dt_num: 0.01
  dt_factor: 5
  batch_size: 40
  nb_traj_train: 40
  nb_traj_val: 40 # test 100
  num_steps_max: 1000

model:
  name: hybrid
  is_augmented: true
  architecture: mlp_angular
  hidden: 200
  init_gain: 1.0
  integration_method: RK4
  dim_state: 4

train:
  lr: 1e-3
  niter: 5
  min_op: l2
  reg_loss_name: loss_AD_sup
  norm: False
  lambda0: 1e-8
  tau2: 0.0
  aux_loss_names: ["loss_AD_sup", "loss_FD_unsup"]
  log_param_error: false # when hybrid
  nlog: 5
  nval: 5 
  curriculum: no_curr
  opt_mode: traj
  finite_diff: forward
  nepoch: 900

experiment:
  path: data_exp/doublependulum_dt005

logging:
  use_wandb: true
  project: DoublePendulumICML
