dataset:
  name: rigidbody
  integration_method: RK4
  duration: 0.5
  dt_num: 0.01
  dt_factor: 10
  batch_size: 40
  nb_traj_train: 40
  nb_traj_val: 40
  num_steps_max: 1500

model:
  name: node
  gamma: 0.1
  aug_option: true
  architecture: "mlp"
  hidden: 200
  init_gain: 1.0
  integration_method: RK4
  dim_state: 3

train:
  lr: 1e-3
  niter: 5
  min_op: l2
  reg_loss_name: loss_AD_single
  norm: False
  lambda0: 1e-12
  tau2: 0.0
  aux_loss_names: ["loss_AD_single"]
  log_param_error: false # when hybrid
  nlog: 5
  nval: 5 
  curriculum: no_curr
  opt_mode: traj
  finite_diff: forward
  nepoch: 900

experiment:
  path: data_exp/rigidbody

logging:
  use_wandb: true
  project: RigidBodyICML
